# Site settings
title: GSoC '15 Tracker
email: ehalbadawy93@gmail.com
description: > # this blog is dedicated to track GSoC prgress
  this blog is dedicated to track GSoC prgress.
baseurl: "/GSoC-Tracker" # the subpath of your site, e.g. /blog/
url: "http://ehab93.github.io" # the base hostname & protocol for your site
github_username:  ehab93

# Build settings
markdown: kramdown
